Update index.html (issue #7)
OrionStar25/Selena-Gomez-Discography pull request #15
Opened 2019-01-12 16:30 UTC by Archies11

I have added the correct soundtrack for the songs "Bang a drum" and "Magic"
The working link : https://archies11.github.io/Selena-Gomez-Discography/

2019-01-12 16:33 UTC, OrionStar25 commented
Please post the working link as well. Read the `readme` file for instructions.

2019-01-12 17:11 UTC, Archies11 commented
Mam Do I post the link here in these comments?

2019-01-12 17:25 UTC, OrionStar25 commented
Yes, post it here :)

2019-01-12 17:30 UTC, OrionStar25 requested changes

2019-01-12 17:30 UTC, OrionStar25 commented on index.html
> +			<a href="https://www.youtube.com/watch?v=3sGXoDxoTPs" class="list-group-item">Bang A Drum</a>
The link doesn't need to change. You have to change the default song in the music player. Right now only one type of song is assigned to each player. Download the song and add it to the player.

2019-01-12 17:30 UTC, OrionStar25 commented on index.html
> +            <a href="https://www.youtube.com/watch?v=Qtb11P1FWnc" class="list-group-item">Magic</a>
Same here.

2019-01-13 05:28 UTC, Archies11 commented on index.html
> +            <a href="https://www.youtube.com/watch?v=Qtb11P1FWnc" class="list-group-item">Magic</a>
Mam i have made the necessary changes.
link: https://archies11.github.io/Selena-Gomez-Discography/

2019-01-13 10:32 UTC, OrionStar25 commented on index.html
> +            <a href="https://www.youtube.com/watch?v=Qtb11P1FWnc" class="list-group-item">Magic</a>
Alright, so you've made the changes the Fetish and Bad Liar. Works good :dancer:

2019-01-13 10:33 UTC, OrionStar25 approved these changes

2019-01-13 10:34 UTC, merged