fixes issue#7:
OrionStar25/Selena-Gomez-Discography pull request #24
Opened 2019-01-14 12:54 UTC by brownsands

issue #7

2019-01-14 12:58 UTC, brownsands commented
Add new classic.mp3 and trust in me.mp3

2019-01-15 07:39 UTC, OrionStar25 requested changes
You're on the right track, but please add a working live link of your fork. Read the `readme`. :+1:

2019-01-15 07:39 UTC, OrionStar25 commented on index.html
> + 			<source src="songs/Made_in_Paris_Trust_Me_Lyndon_Kidd_Remix_(mp3co.info)"
This song is wrong. You have to add `Trust in Me by Selena Gomez`.

2019-01-15 13:42 UTC, brownsands commented
https://brownsands.github.io/Selena-Gomez-Discography/

2019-01-15 16:59 UTC, OrionStar25 approved these changes
Great work! :fire:

2019-01-15 17:00 UTC, merged