Fixes #27 : Music player comes out of the singles list on resizing
OrionStar25/Selena-Gomez-Discography pull request #30
Opened 2019-01-15 20:23 UTC by supremenishant

https://github.com/supremenishant/Selena-Gomez-Discography.git

2019-01-16 16:11 UTC, OrionStar25 commented
@supremenishant please post the working link of your fork(published website of your fork). Read the `readme` for reference.

2019-01-16 16:11 UTC, OrionStar25 requested changes
Code mostly seems fine. :+1:

2019-01-16 17:40 UTC, supremenishant commented
https://supremenishant.github.io/Selena-Gomez-Discography/

2019-01-17 12:42 UTC, OrionStar25 approved these changes

2019-01-17 12:42 UTC, merged