overlap songs above tiles closes #42
OrionStar25/Selena-Gomez-Discography pull request #49
Opened 2019-01-21 13:21 UTC by sourabh1031

* Please fill out the template below

### Did you read the instructions in [README](../README.md) ?

>Yes
### Solves which issue ?

>Solves #42
### Give discription.

>[Write Here. Be Specific]

2019-01-22 06:58 UTC, pradeepgangwar commented
@sourabh1031 Please provide a live link to review changes.

2019-01-22 07:04 UTC, sourabh1031 commented
https://sourabh1031.github.io/Selena-Gomez-Discography/

2019-01-22 15:37 UTC, OrionStar25 requested changes
You have merge conflicts. Please try to remove them.

2019-01-22 15:37 UTC, OrionStar25 commented on css/theme.css
> +        z-index: -1;
I think `z-index` should be positive. Right now, album tiles are overlapping the songs. We need the opposite.

2019-01-23 14:47 UTC, OrionStar25 commented
Still not working for mobile view. Please check if the commit works on your local link before committing.

2019-01-23 17:11 UTC, sourabh1031 commented
@OrionStar25 i think now it works.

2019-01-24 17:09 UTC, OrionStar25 commented
Still not working. 
![screenshot from 2019-01-24 22-37-32](https://user-images.githubusercontent.com/28835849/51695369-e7212300-2028-11e9-9b02-588d50ed2644.png)

2019-01-25 07:05 UTC, closed without merging